version: '3.8'

services:
  db:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: motec4thepeople
      MYSQL_DATABASE: motec_db
      MYSQL_USER: motec
      MYSQL_PASSWORD: motec4thepeople
    ports:
      - "3306:3306"
    volumes:
      - ./backend/database:/var/lib/mysql
  web:
    build:
      context: frontend
      dockerfile: Dockerfile
    depends_on: 
      - db
    expose:
      - 80
    volumes:
      - ./frontend/:/var/www/html/
      - /var/lib/motec:/srv/motec_data
      - /var/lib/motec_upload:/uploads
    environment:
      VIRTUAL_HOST: motec.ascaroth.de
  loader:
    build:
      context: ./loader
      dockerfile: Dockerfile
    depends_on: 
      - db
    environment:
      MOTEC_PATH: "/motec_data"
      UPLOADS_PATH: "/uploads"
      MYSQL_HOST: db
      MYSQL_DATABASE: motec_db
      MYSQL_USER: motec
      MYSQL_PASSWORD: motec4thepeople
    volumes:
      - /var/lib/motec:/motec_data
      - /var/log/:/var/log/
      - /var/lib/motec_upload:/uploads

networks:
  default:
    external:
      name: nginx-proxy
