version: '3.8'

services:
  db:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: motec4thepeople
      MYSQL_DATABASE: motec_db
      MYSQL_USER: motec
      MYSQL_PASSWORD: motec4thepeople
    ports:
      - "3306:3306"
    volumes:
      - ./backend/database:/var/lib/mysql
  web:
    build:
      context: frontend
      dockerfile: Dockerfile
    depends_on: 
      - db
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/:/var/www/html/
  loader:
    build:
      context: ./loader
      dockerfile: Dockerfile
    depends_on: 
      - db
    environment:
      DATA_PATH: "/motec_data"
      MYSQL_HOST: db
      MYSQL_DATABASE: motec_db
      MYSQL_USER: motec
      MYSQL_PASSWORD: motec4thepeople
    volumes:
      - /mnt/projects/ACCmotec/motec_data:/motec_data
